### ISSUE TITLE
Cannot find module 'lodash.clonedeep' from 'node_modules/slate-test-utils/dist/cjs/ensureSlateValid.js'

### ISSUE THREAD

**Issue by rzachariah** [mwood23/slate-test-utils#7]
I tried cloning your example, basically as is, and I'm getting errors on `npm test`.

eg
```
npm test

> slate-example@0.0.0 test
> jest --verbose

 FAIL  src/tests/ensure-valid.test.tsx
  ● Test suite failed to run

    Cannot find module 'lodash.clonedeep' from 'node_modules/slate-test-utils/dist/cjs/ensureSlateValid.js'

    Require stack:
      node_modules/slate-test-utils/dist/cjs/ensureSlateValid.js
      node_modules/slate-test-utils/dist/cjs/buildTestHarness.js
      node_modules/slate-test-utils/dist/cjs/index.js
      src/tests/ensure-valid.test.tsx

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (node_modules/slate-test-utils/dist/cjs/ensureSlateValid.js:5:28)
```

You can find an example repo here.
https://github.com/rzachariah/slate-example

**Comment by mwood23** [comment]
@rzachariah Thanks for opening. Had that dep as a `devDependency` accidentally. Just published 1.3.1 where it's be fixed! Commit: https://github.com/mwood23/slate-test-utils/commit/93e26f2bdde43e5185a39f46d19538164b3e1d8b. Lemme know if you run into any else.
